# Site settings
author: Joann Brady
title: Joann Brady
header-img: img/home-bg.png
email: jbrady11934@optimum.net
copyright_name: Joann Brady
description: > # this means to ignore newlines until "baseurl:"
  Why I Decided to learn Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JoJoVil

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
